// src/app/shared/cache-keys.ts
export const CACHE_KEYS = {
  CATEGORIES: 'CACHE_CATEGORIES',
  PRODUCTS: 'CACHE_PRODUCTS',
  CLIENTS: 'CACHE_CLIENTS',
  EMPLOYEES: 'CACHE_EMPLOYEES',
  LAST_SYNC: 'CACHE_LAST_SYNC'
};
